global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:4000']

  - job_name: 'media_service'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'cache'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'database'
    static_configs:
      - targets: ['localhost:5432']